# Generated by Django 5.0.4 on 2024-04-26 16:45

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, max_length=128, verbose_name='Никнейм')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.SmallIntegerField(default=0, verbose_name='Шаг опроса')),
                ('parts', jsonfield.fields.JSONField(default=dict, max_length=8192, verbose_name='Варианты')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершенные опросы')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='clientbanan.respondent', verbose_name='Респондент')),
            ],
        ),
    ]
